################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (9-2020-q2-update)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/src/misc.c \
F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/src/stm32f401re_adc.c \
F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/src/stm32f401re_dma.c \
F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/src/stm32f401re_exti.c \
F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/src/stm32f401re_gpio.c \
F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/src/stm32f401re_i2c.c \
F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/src/stm32f401re_rcc.c \
F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/src/stm32f401re_spi.c \
F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/src/stm32f401re_syscfg.c \
F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/src/stm32f401re_tim.c \
F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/src/stm32f401re_usart.c 

OBJS += \
./SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/src/misc.o \
./SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/src/stm32f401re_adc.o \
./SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/src/stm32f401re_dma.o \
./SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/src/stm32f401re_exti.o \
./SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/src/stm32f401re_gpio.o \
./SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/src/stm32f401re_i2c.o \
./SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/src/stm32f401re_rcc.o \
./SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/src/stm32f401re_spi.o \
./SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/src/stm32f401re_syscfg.o \
./SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/src/stm32f401re_tim.o \
./SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/src/stm32f401re_usart.o 

C_DEPS += \
./SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/src/misc.d \
./SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/src/stm32f401re_adc.d \
./SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/src/stm32f401re_dma.d \
./SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/src/stm32f401re_exti.d \
./SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/src/stm32f401re_gpio.d \
./SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/src/stm32f401re_i2c.d \
./SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/src/stm32f401re_rcc.d \
./SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/src/stm32f401re_spi.d \
./SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/src/stm32f401re_syscfg.d \
./SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/src/stm32f401re_tim.d \
./SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/src/stm32f401re_usart.d 


# Each subdirectory must supply rules for building sources it contributes
SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/src/misc.o: F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/src/misc.c SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DNUCLEO_F401RE -DSTM32 -DSTM32F401RETx -DSTM32F4 -c -I"F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/CMSIS/Include" -I"F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/inc" -I"F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/button" -I"F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/buzzer" -I"F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/led" -I"F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/rtos" -I"F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/sensor" -I"F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/serial" -I"F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib" -I"F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Utilities" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/src/stm32f401re_adc.o: F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/src/stm32f401re_adc.c SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DNUCLEO_F401RE -DSTM32 -DSTM32F401RETx -DSTM32F4 -c -I"F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/CMSIS/Include" -I"F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/inc" -I"F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/button" -I"F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/buzzer" -I"F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/led" -I"F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/rtos" -I"F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/sensor" -I"F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/serial" -I"F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib" -I"F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Utilities" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/src/stm32f401re_dma.o: F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/src/stm32f401re_dma.c SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DNUCLEO_F401RE -DSTM32 -DSTM32F401RETx -DSTM32F4 -c -I"F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/CMSIS/Include" -I"F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/inc" -I"F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/button" -I"F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/buzzer" -I"F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/led" -I"F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/rtos" -I"F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/sensor" -I"F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/serial" -I"F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib" -I"F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Utilities" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/src/stm32f401re_exti.o: F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/src/stm32f401re_exti.c SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DNUCLEO_F401RE -DSTM32 -DSTM32F401RETx -DSTM32F4 -c -I"F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/CMSIS/Include" -I"F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/inc" -I"F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/button" -I"F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/buzzer" -I"F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/led" -I"F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/rtos" -I"F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/sensor" -I"F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/serial" -I"F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib" -I"F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Utilities" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/src/stm32f401re_gpio.o: F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/src/stm32f401re_gpio.c SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DNUCLEO_F401RE -DSTM32 -DSTM32F401RETx -DSTM32F4 -c -I"F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/CMSIS/Include" -I"F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/inc" -I"F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/button" -I"F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/buzzer" -I"F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/led" -I"F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/rtos" -I"F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/sensor" -I"F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/serial" -I"F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib" -I"F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Utilities" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/src/stm32f401re_i2c.o: F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/src/stm32f401re_i2c.c SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DNUCLEO_F401RE -DSTM32 -DSTM32F401RETx -DSTM32F4 -c -I"F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/CMSIS/Include" -I"F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/inc" -I"F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/button" -I"F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/buzzer" -I"F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/led" -I"F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/rtos" -I"F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/sensor" -I"F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/serial" -I"F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib" -I"F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Utilities" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/src/stm32f401re_rcc.o: F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/src/stm32f401re_rcc.c SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DNUCLEO_F401RE -DSTM32 -DSTM32F401RETx -DSTM32F4 -c -I"F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/CMSIS/Include" -I"F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/inc" -I"F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/button" -I"F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/buzzer" -I"F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/led" -I"F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/rtos" -I"F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/sensor" -I"F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/serial" -I"F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib" -I"F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Utilities" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/src/stm32f401re_spi.o: F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/src/stm32f401re_spi.c SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DNUCLEO_F401RE -DSTM32 -DSTM32F401RETx -DSTM32F4 -c -I"F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/CMSIS/Include" -I"F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/inc" -I"F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/button" -I"F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/buzzer" -I"F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/led" -I"F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/rtos" -I"F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/sensor" -I"F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/serial" -I"F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib" -I"F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Utilities" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/src/stm32f401re_syscfg.o: F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/src/stm32f401re_syscfg.c SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DNUCLEO_F401RE -DSTM32 -DSTM32F401RETx -DSTM32F4 -c -I"F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/CMSIS/Include" -I"F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/inc" -I"F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/button" -I"F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/buzzer" -I"F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/led" -I"F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/rtos" -I"F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/sensor" -I"F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/serial" -I"F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib" -I"F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Utilities" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/src/stm32f401re_tim.o: F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/src/stm32f401re_tim.c SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DNUCLEO_F401RE -DSTM32 -DSTM32F401RETx -DSTM32F4 -c -I"F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/CMSIS/Include" -I"F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/inc" -I"F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/button" -I"F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/buzzer" -I"F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/led" -I"F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/rtos" -I"F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/sensor" -I"F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/serial" -I"F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib" -I"F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Utilities" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/src/stm32f401re_usart.o: F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/src/stm32f401re_usart.c SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DNUCLEO_F401RE -DSTM32 -DSTM32F401RETx -DSTM32F4 -c -I"F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/CMSIS/Include" -I"F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Drivers/STM32F401RE_StdPeriph_Driver/inc" -I"F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/button" -I"F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/buzzer" -I"F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/led" -I"F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/rtos" -I"F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/sensor" -I"F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/serial" -I"F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Middle/ucglib" -I"F:/IoT/Application/thuvien/show/SDK_1.0.3_NUCLEO-F401RE/shared/Utilities" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

